
name: Hexo Auto-Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Hexo Auto-Deploy by GitHub Actions
    runs-on: ubuntu-latest

    steps:
    - name: 1. git checkout...
      uses: actions/checkout@v1
      
    - name: 2. setup nodejs...
      uses: actions/setup-node@v1
    
    - name: 3. install hexo...
      run: |
        npm install hexo-cli -g
        npm install hexo-deployer-git
        npm install
        
    - name: 4. hexo generate public files...
      run: |
        hexo clean
        hexo g  

    - name: 5. hexo config ...
      env:
          ACTION_DEPLOY_KEY: ${{ secrets.hexo }}
      run: |
          # set up private key for deploy
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          # set git infomation
          git config --global user.name 'xpfyg'
          git config --global user.email '997052247@qq.com'
          # install dependencies
          npm i -g hexo-cli
          npm i
     
    - name: 6. hexo deploy ...
      run: 
        hexo d
